### ISSUE TITLE
Really appreciate your work

### ISSUE THREAD

**Issue by bongikairu** [Dingf/Source-2-Decompiler#1]
Hi, I would like to thank you for your work on this decompiler. I've studied your code and managed to write my own version for my current project (which would take quite some time to do on my own). If you want to check it out, the code is here:

[https://github.com/bongikairu/flare/blob/master/engine/kvreader2.hpp](https://github.com/bongikairu/flare/blob/master/engine/kvreader2.hpp)
[https://github.com/bongikairu/flare/blob/master/engine/kvreader2.cpp](https://github.com/bongikairu/flare/blob/master/engine/kvreader2.cpp)
[https://github.com/bongikairu/flare/blob/master/vtexInfo.cpp](https://github.com/bongikairu/flare/blob/master/vtexInfo.cpp)

**Comment by Dingf** [comment]
I'm glad you found it useful. Best of luck on your project.
