### ISSUE TITLE
vtex_c files which contain TGA compressed with DXT5 have incorrect colors when decompressed

### ISSUE THREAD

**Issue by babelshift** [Dingf/Source-2-Decompiler#4]
After some testing and research, I've found that the vtex_c files which are incorrectly colored on extraction are TGA files compressed with DXT5 and possibly in YCoCg colorspace.

Looking at the file in a hex editor reveals:

CResourceString m_String = "Texture Compiler Version Image YCoCg Conversion"

This is a bit out of my league. I'm not sure if Valve's texture compiler is converting to YCoCg colorspace prior to compression. Maybe that means it needs to be read out as YCoCg and converted to RGB during decompression?

Github doesn't support attaching vtex_c, but here's a test file that you can see. https://drive.google.com/file/d/0B7o2acNuwX44X01LZnVUeFZfX2c/view?usp=sharing

Attached to this issue is the results of decompressing the file linked above.
![loadingscreen_tga](https://cloud.githubusercontent.com/assets/2723423/11454228/10cb83d0-95f3-11e5-8f9f-05dca549e2b5.png)

**Comment by Dingf** [comment]
Thanks for the heads up. I haven't had much time to work on the project lately, but I will try to schedule some time to take a look sometime later this week. If I remember correctly, one problem I had before was that there was no way to tell a YCoCg vtex_c file apart from a normal DXT5 file. Maybe Valve has added something since then.

**Comment by babelshift** [comment]
I don't know enough about color theory and related algorithms to detect color space within an image, but I do know that some of the vtex_c metadata contains references to things like "YCoCg conversion". Not sure if that's helpful though.

**Comment by babelshift** [comment]
Some info from this thread which might be relevant: http://dev.dota2.com/showthread.php?t=182677&page=2

> Okey.
> 
> Good news. The format used`s definitely YCgCo (https://en.wikipedia.org/wiki/YCgCo). I`ve managed to compile a YCgCo formatted image using it`s Valve-spinoff, and my Dota 2 client displayed it correctly. The schema Valve`s using`s the following:
> R: Co
> G: Cg
> B: Edit: Nope, it`s not Alpha. It`s .. something. Can`t discern what, tho.
> A: Y

**Comment by babelshift** [comment]
See more on this issue for a possible solution. Though this assumes YCgCo color space. I am not sure how to detect the color space from the meta data.

https://github.com/SteamDatabase/ValveResourceFormat/issues/29#issuecomment-161052606

**Comment by Dingf** [comment]
Added YCoCg support a while back but forgot to close this. Closing the issue now.
